// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// WatersColumns holds the columns for the "waters" table.
	WatersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "liters", Type: field.TypeFloat64},
		{Name: "topic", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// WatersTable holds the schema information for the "waters" table.
	WatersTable = &schema.Table{
		Name:       "waters",
		Columns:    WatersColumns,
		PrimaryKey: []*schema.Column{WatersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WatersTable,
	}
)

func init() {
}
