// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"minimal/ent/migrate"

	"minimal/ent/water"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Water is the client for interacting with the Water builders.
	Water *WaterClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Water = NewWaterClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Water:  NewWaterClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Water:  NewWaterClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Water.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Water.Use(hooks...)
}

// WaterClient is a client for the Water schema.
type WaterClient struct {
	config
}

// NewWaterClient returns a client for the Water from the given config.
func NewWaterClient(c config) *WaterClient {
	return &WaterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `water.Hooks(f(g(h())))`.
func (c *WaterClient) Use(hooks ...Hook) {
	c.hooks.Water = append(c.hooks.Water, hooks...)
}

// Create returns a builder for creating a Water entity.
func (c *WaterClient) Create() *WaterCreate {
	mutation := newWaterMutation(c.config, OpCreate)
	return &WaterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Water entities.
func (c *WaterClient) CreateBulk(builders ...*WaterCreate) *WaterCreateBulk {
	return &WaterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Water.
func (c *WaterClient) Update() *WaterUpdate {
	mutation := newWaterMutation(c.config, OpUpdate)
	return &WaterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WaterClient) UpdateOne(w *Water) *WaterUpdateOne {
	mutation := newWaterMutation(c.config, OpUpdateOne, withWater(w))
	return &WaterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WaterClient) UpdateOneID(id int) *WaterUpdateOne {
	mutation := newWaterMutation(c.config, OpUpdateOne, withWaterID(id))
	return &WaterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Water.
func (c *WaterClient) Delete() *WaterDelete {
	mutation := newWaterMutation(c.config, OpDelete)
	return &WaterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WaterClient) DeleteOne(w *Water) *WaterDeleteOne {
	return c.DeleteOneID(w.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WaterClient) DeleteOneID(id int) *WaterDeleteOne {
	builder := c.Delete().Where(water.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WaterDeleteOne{builder}
}

// Query returns a query builder for Water.
func (c *WaterClient) Query() *WaterQuery {
	return &WaterQuery{
		config: c.config,
	}
}

// Get returns a Water entity by its id.
func (c *WaterClient) Get(ctx context.Context, id int) (*Water, error) {
	return c.Query().Where(water.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WaterClient) GetX(ctx context.Context, id int) *Water {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WaterClient) Hooks() []Hook {
	return c.hooks.Water
}
