// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"minimal/ent/predicate"
	"minimal/ent/water"
	"sync"
	"time"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeWater = "Water"
)

// WaterMutation represents an operation that mutates the Water nodes in the graph.
type WaterMutation struct {
	config
	op            Op
	typ           string
	id            *int
	liters        *float64
	addliters     *float64
	topic         *string
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Water, error)
	predicates    []predicate.Water
}

var _ ent.Mutation = (*WaterMutation)(nil)

// waterOption allows management of the mutation configuration using functional options.
type waterOption func(*WaterMutation)

// newWaterMutation creates new mutation for the Water entity.
func newWaterMutation(c config, op Op, opts ...waterOption) *WaterMutation {
	m := &WaterMutation{
		config:        c,
		op:            op,
		typ:           TypeWater,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withWaterID sets the ID field of the mutation.
func withWaterID(id int) waterOption {
	return func(m *WaterMutation) {
		var (
			err   error
			once  sync.Once
			value *Water
		)
		m.oldValue = func(ctx context.Context) (*Water, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Water.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withWater sets the old Water of the mutation.
func withWater(node *Water) waterOption {
	return func(m *WaterMutation) {
		m.oldValue = func(context.Context) (*Water, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m WaterMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m WaterMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *WaterMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *WaterMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Water.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetLiters sets the "liters" field.
func (m *WaterMutation) SetLiters(f float64) {
	m.liters = &f
	m.addliters = nil
}

// Liters returns the value of the "liters" field in the mutation.
func (m *WaterMutation) Liters() (r float64, exists bool) {
	v := m.liters
	if v == nil {
		return
	}
	return *v, true
}

// OldLiters returns the old "liters" field's value of the Water entity.
// If the Water object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WaterMutation) OldLiters(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLiters is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLiters requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLiters: %w", err)
	}
	return oldValue.Liters, nil
}

// AddLiters adds f to the "liters" field.
func (m *WaterMutation) AddLiters(f float64) {
	if m.addliters != nil {
		*m.addliters += f
	} else {
		m.addliters = &f
	}
}

// AddedLiters returns the value that was added to the "liters" field in this mutation.
func (m *WaterMutation) AddedLiters() (r float64, exists bool) {
	v := m.addliters
	if v == nil {
		return
	}
	return *v, true
}

// ResetLiters resets all changes to the "liters" field.
func (m *WaterMutation) ResetLiters() {
	m.liters = nil
	m.addliters = nil
}

// SetTopic sets the "topic" field.
func (m *WaterMutation) SetTopic(s string) {
	m.topic = &s
}

// Topic returns the value of the "topic" field in the mutation.
func (m *WaterMutation) Topic() (r string, exists bool) {
	v := m.topic
	if v == nil {
		return
	}
	return *v, true
}

// OldTopic returns the old "topic" field's value of the Water entity.
// If the Water object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WaterMutation) OldTopic(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTopic is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTopic requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTopic: %w", err)
	}
	return oldValue.Topic, nil
}

// ResetTopic resets all changes to the "topic" field.
func (m *WaterMutation) ResetTopic() {
	m.topic = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *WaterMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *WaterMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Water entity.
// If the Water object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WaterMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *WaterMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the WaterMutation builder.
func (m *WaterMutation) Where(ps ...predicate.Water) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *WaterMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Water).
func (m *WaterMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *WaterMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.liters != nil {
		fields = append(fields, water.FieldLiters)
	}
	if m.topic != nil {
		fields = append(fields, water.FieldTopic)
	}
	if m.created_at != nil {
		fields = append(fields, water.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *WaterMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case water.FieldLiters:
		return m.Liters()
	case water.FieldTopic:
		return m.Topic()
	case water.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *WaterMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case water.FieldLiters:
		return m.OldLiters(ctx)
	case water.FieldTopic:
		return m.OldTopic(ctx)
	case water.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Water field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WaterMutation) SetField(name string, value ent.Value) error {
	switch name {
	case water.FieldLiters:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLiters(v)
		return nil
	case water.FieldTopic:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTopic(v)
		return nil
	case water.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Water field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *WaterMutation) AddedFields() []string {
	var fields []string
	if m.addliters != nil {
		fields = append(fields, water.FieldLiters)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *WaterMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case water.FieldLiters:
		return m.AddedLiters()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WaterMutation) AddField(name string, value ent.Value) error {
	switch name {
	case water.FieldLiters:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLiters(v)
		return nil
	}
	return fmt.Errorf("unknown Water numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *WaterMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *WaterMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *WaterMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Water nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *WaterMutation) ResetField(name string) error {
	switch name {
	case water.FieldLiters:
		m.ResetLiters()
		return nil
	case water.FieldTopic:
		m.ResetTopic()
		return nil
	case water.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Water field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *WaterMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *WaterMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *WaterMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *WaterMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *WaterMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *WaterMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *WaterMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Water unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *WaterMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Water edge %s", name)
}
