// Code generated by ent, DO NOT EDIT.

package water

import (
	"time"
)

const (
	// Label holds the string label denoting the water type in the database.
	Label = "water"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLiters holds the string denoting the liters field in the database.
	FieldLiters = "liters"
	// FieldTopic holds the string denoting the topic field in the database.
	FieldTopic = "topic"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the water in the database.
	Table = "waters"
)

// Columns holds all SQL columns for water fields.
var Columns = []string{
	FieldID,
	FieldLiters,
	FieldTopic,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
